language: php

php:
  - '7.0'
  - '5.6'
  - '5.5'

env:
  global:
    - WP_THEME=https://github.com/WordPress/twentysixteen/archive/master.zip
  matrix:
    - WP_VERSION=nightly
    - WP_VERSION=latest

before_install:
  - nvm install node
  - nvm alias default node
  - node --version
  - npm install
  - npm run init
  - npm run install-wp
  - npm run wp >/dev/null 2>&1 &

script:
  - npm test
