language: php

php:
  - '7.0'
  - '5.6'

env:
  matrix:
    - WP_THEME=https://downloads.wordpress.org/theme/twentysixteen.1.3.zip
    - WP_THEME=https://downloads.wordpress.org/theme/twentyfifteen.1.6.zip

before_install:
  - npm install
  - npm run init
  - npm run wp-install
  - npm run wp >/dev/null 2>&1 &

script:
  - npm test
