language: php

php:
- '7.0'

env:
  global:
    - WP_PATH=/tmp/wordpress
    - WP_PORT=8080
    - WP_THEME=https://downloads.wordpress.org/theme/twentysixteen.1.3.zip
  matrix:
    - WP_THEME=https://downloads.wordpress.org/theme/twentysixteen.1.3.zip
    - WP_THEME=https://downloads.wordpress.org/theme/twentyfifteen.1.6.zip

before_install:
  - composer install
  - mysql -e "create database IF NOT EXISTS wordpress;" -uroot
  - bash init/install-wp.sh
  - ./wp-cli-nightly.phar server --host=0.0.0.0 --port=$WP_PORT --docroot=$WP_PATH --path=$WP_PATH >/dev/null 2>&1 &
  - npm install
  - npm start

script:
  - npm test
